### PR TITLE
docs: add ropensci concept to appease pkgdown::check_pkgdown()

### PR DESCRIPTION
**Pull request by maelle**

### CODE REVIEW

**Comment by mpadge** [comment]
I can't even get `check_pkgdown()` to work at all on my system, so will have to trust you on that one. But isn't there also a missing tag for the previous, `readme_badge` fn?

**Comment by maelle** [comment]
is it exported though? pkgdown didn't complain about it

**Comment by mpadge** [comment]
Yeah, they're all exported (coz they have to be for this pkg to work). `check_pkgdown()` should definitely fail here, but it doesn't complain for me at all. And yet, when i need it on lots of other packages, it fails even when i know i've done everything right. Grumble grumble ... :bear:

**Comment by maelle** [comment]
`readme_badge` is actually listed directly in the config! so good to merge. sorry to hear about the function not working for you, it's so handy :sob:

**Pull request merged**
